services:
  Icecast2:
    image: riftbit/icecast:1.3.0
    ports: 
    - 8000:8000
    restart: always
    environment:
      ICE_RADIO_LISTEN_PORT: 8000
      ICE_RADIO_HOSTNAME: "radio.icecast2.com"
      ICE_RADIO_LOG_LEVEL: 4
      ICE_RADIO_MAX_CLIENTS: 500
      ICE_RADIO_MAX_SOURCES: 1
      ICE_RADIO_ADMIN_PASSWORD: admin
      ICE_RADIO_SOURCE_PASSWORD: source123
      ICE_RADIO_RELAY_PASSWORD: admin123
      ICE_RADIO_LOCATION: "Radio Icecast2"
      ICE_RADIO_ADMIN_CONTACT: www.radio@icecast2.com
      ICE_RADIO_ADDITIONAL_CONFIGS: "<directory></directory>"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - logs:/var/log/ices:rw
    networks:
      - public_icecast
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1' # hard processing
          memory: 512M # hard caching
      placement:
        constraints:
          - node.role == worker
          - node.labels.can-run-icecast == yes

  Traefik:
    image: traefik:v3
    restart: always
    container_name: Traefik
    command:
      - '--api.dashboard=true'
      - '--providers.docker=true'
      - '--providers.file.filename=/etc/traefik/traefik_dynamic.yml'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.myresolver.acme.email=pedrowilmannpires@gmail.com' # Substitua pelo seu email
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './letsencrypt:/letsencrypt'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml' # Monta o arquivo de configuração dinâmica
    networks:
      - public_icecast
    labels:
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik-dev.com)"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik-dashboard.middlewares=dashboard-auth@file" # Descomente para ativar autenticação


networks:
  public_icecast:
    external: true

volumes:
  logs:
  